### ISSUE TITLE
Run sync when simulation paused

### ISSUE THREAD

**Issue by zdimension** [Jondolf/bevy_xpbd#87] opened 2023-07-19 01:06 UTC
Currently, if an object is moved while the simulation is paused, its transform is not updated, so the collision queries for example will not work until the simulation is resumed

**Comment by Jondolf** [comment] 2023-07-28 19:59
Hi, sorry for the late reply.

Doesn't sync already run even if the simulation is paused? [It runs in `PostUpdate` by default](https://github.com/Jondolf/bevy_xpbd/blob/e3f3b8fcd99d1a03de1cb48834c92eb6c2a09279/src/plugins/sync.rs#L33), so it shouldn't matter if the `PhysicsSchedule` is paused.

It's somewhat intended that things like collision detection don't run when the simulation is paused since it would just be wasting resources when nothing is happening physics-wise.

**Comment by zdimension** [comment] 2023-07-28 20:34
> Hi, sorry for the late reply.
> 
> Doesn't sync already run even if the simulation is paused? [It runs in `PostUpdate` by default](https://github.com/Jondolf/bevy_xpbd/blob/e3f3b8fcd99d1a03de1cb48834c92eb6c2a09279/src/plugins/sync.rs#L33) (although I'm adding more syncing functionality, see #96), so it shouldn't matter if the `PhysicsSchedule` is paused.
> 
> It's somewhat intended that things like collision detection don't run when the simulation is paused since it would just be wasting resources when nothing is happening physics-wise.

Hey, thanks for taking the time to look into this!

Basically l my use case is that I'm making a 2d physics simulator where you can draw shapes and stuff, and I use collision queries to know, for example, what object the user has clicked. But say that the simulation is paused, then if I move an object, it doesn't move its collider, so all mouse events are "wrong" until I resume the simulation

So I'm not trying to make the collision detection routines run constantly, but I want to be able to update the state (position) of the colliders while it's paused and then make collision queries without having to resume

(Sorry if unclear)

**Comment by Jondolf** [comment] 2023-07-28 21:34
Are you using [point projection](https://docs.rs/bevy_xpbd_2d/0.2.0/bevy_xpbd_2d/plugins/spatial_query/index.html#point-projection) for getting the clicked entity, or an actual collider positioned at the cursor? Point projection is definitely the easier option.

The collider's position is the same as the body's position (currently), so it should be getting updated even when the simulation is paused. If you're using spatial queries like point projection, I think the problem is that the internal [spatial query pipeline](https://docs.rs/bevy_xpbd_2d/0.2.0/bevy_xpbd_2d/plugins/spatial_query/struct.SpatialQueryPipeline.html) (contains a hash map of colliders for spatial queries) is updated by the `PhysicsSchedule`, which doesn't run if the simulation is paused.

For now, you can call `.update_pipeline()` for the `SpatialQuery` system parameter before you run the queries. I could probably update the pipeline outside of the `PhysicsSchedule` as well, but that might add a bit of extra overhead.

I might be misunderstanding what you mean by collision queries though. If you mean spawning an actual collider at the cursor position, then checking for a collision when the simulation is paused isn't possible currently, so I would recommend using spatial queries instead.

**Comment by zdimension** [comment] 2023-07-28 21:42
I'm using point projection

Yeah, when I said collision queries I just meant the point projection, spatial queries was the proper term

I'll try using `update_pipelines`, thanks!

**Comment by Jondolf** [comment] 2023-07-31 12:42
I'll assume it works so I'll close this now. Feel free to reopen if you have any issues

**Comment by zdimension** [comment] 2023-07-31 12:43
Yep, sorry, forgot to write here, it works perfectly, thanks!

**Closed by Jondolf** 2023-07-31 12:42 UTC
Labels: enhancement
